#/run/numberOfThreads 1
/control/verbose 2
/control/saveHistory
/run/verbose 2
/run/initialize
#/vis/open OGL 600x600-0+0
#/vis/viewer/set/viewpointVector 1 1 1
#/vis/drawVolume
#/vis/viewer/set/autoRefresh false
#/vis/scene/add/trajectories smooth
#/vis/scene/add/axes
#/vis/scene/add/eventID
#/vis/scene/endOfEventAction accumulate

#This is for atmospheric shower
#/vis/ogl/set/displayListLimit 5000000

#If you want to add a scale in the viewer
#/vis/scene/add/scale 10 cm 
